### ISSUE TITLE
Search Filters: Scrollbar is Missing

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#104]
I am 99% sure there was a scrollbar in filters on a past review, but it is gone now, so when you open a filter accordion it fills the space like this:

![Screen Shot 2023-09-07 at 3 52 28 PM](https://github.com/ucd-library/dams/assets/17831969/8e8a4283-b507-40ef-ab61-8db538eb2d02)

when it should be something more like this:

![Screen Shot 2023-09-07 at 4 03 08 PM](https://github.com/ucd-library/dams/assets/17831969/bcedc6c7-fc88-422d-b229-dd1a46ce5a47)

**Comment by UcDust** [comment]
@wrenaria I see what's going on. There's a different non-overflow/scrollable list view that's populated if there are more than 50 items in a filter. I hadn't seen as I don't have that many items in my dev environment.

I've removed that so everything should use the scrollable list now.
