### ISSUE TITLE
Firefox: remove scrollbar theming

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#111]
Am I imagining things or is the site's scrollbar themed to be gold on Firefox? I don't see this on other browsers. Please remove, it's super distracting. Default scrollbar only.

![Screen Shot 2023-09-07 at 5 08 11 PM](https://github.com/ucd-library/dams/assets/17831969/56eb1494-f262-459c-8758-f18091524c8b)

**Comment by UcDust** [comment]
@wrenaria 

I can't seem to replicate this. Is it still an issue for you? If so, could you let me know which Firefox version you're running?

**Comment by wrenaria** [comment]
@UcDust It's gone now. Mysterious.
