### ISSUE TITLE
Change homepage feature image on load

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#127]
The homepage feature image should change on page load and display item name + collection name as linked text in the "Featured image" area below the homepage search. 

if item names are super long, we may want to set a character limit and truncate them with "..." appended to not fill up the page with text (Items from California Agricultural Teaching Aid Photograph Collection come to mind -- some of them are straight up paragraphs.)

Old mockup showing examples of different backgrounds in place: https://xd.adobe.com/view/6920e9b1-29fa-474e-a43b-14031b014b3a-3c73/

![Screenshot 2023-10-25 at 10 26 14 AM](https://github.com/ucd-library/dams/assets/17831969/d5257cc8-81e0-4389-b2df-3e8cd94c12d5)

Images for this can be found on Drive at https://drive.google.com/drive/folders/1fOtphSi5EXPtYr528_1rd6bPe6UcsTC5?usp=drive_link

There is a spreadsheet of the items here: https://docs.google.com/spreadsheets/d/1GOSHbJntn-IcVVnOycvnPIhj5d94dEdr6RpaTVlCRJY/edit#gid=0

...but it's over a year old so the links may be incorrect for some of them. If you want me to go through and update URL or change out the item link to be ark id or something, let me know.

We will likely also want to add images now and then as content expands, no more than a couple times a year or less. There doesn't necessarily need to be a dedicated user facing UI for this in DAMS, but we will need to define a workflow for me to provide new images and item/collection data for this purpose (could be as simple as supplying it via GitHub issue and label/tagging assignees correctly, but let me know if you have other thoughts.)

**Comment by UcDust** [comment]
Probably the easiest approach for adding more item/collection data would be to just to create a GitHub issue. 

It's possible we could provide some steps to upload into fcrepo, but we'll also need to add the image asset and references to the item/collection links/labels into the init code in the dams repo, and potentially restart the services, for them to show up.
