### ISSUE TITLE
[UX/UI] Collection Numbers don't match item count 

### ISSUE THREAD

**Issue by qjhart** [ucd-library/dams#215]
**Describe the bug**
The total number of items in a collection doesn't match what you see when visiting the collection in some cases.

![image](https://github.com/user-attachments/assets/cfe3ea11-647d-40a5-b66d-a35775d670ad)
![image](https://github.com/user-attachments/assets/41fea021-c9d9-45a4-b8a1-af9c7dfad8f5)

**Comment by UcDust** [comment]
@qjhart @jrmerz 

I'm closing this issue. It seems reindexing the collections fixed the issue. The `itemCount` (pretty sure) is part of the collection transform, and I'm guessing there was some race condition or something where the collection indexing finished before all the items were indexed. I reindexed the 3 collections that had this issue and things look good now. 

The affected collections were:
https://dev.dams.library.ucdavis.edu/collection/ark:/13030/c8154mgs
https://dev.dams.library.ucdavis.edu/collection/ark:/87287/d79c7b
https://dev.dams.library.ucdavis.edu/collection/ark:/87293/d3f766f0g
