### ISSUE TITLE
[UX/UI] Search results reordering strangely or loading wrong item

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#219]
Ran into some strangeness while exploring the Picnic Day collection.

- A URL is appearing the filters sidebar. I've only seen this happen when selecting Picnic Day. 
- The results are randomly changing order and/or showing the wrong thing when you click back and forth between search and viewing items.
- The "from 1 collection' text flashes visible for a moment on search page every time it loads and then vanishes.

See the video below for more detail.

https://github.com/user-attachments/assets/49e02788-620a-4902-b75d-a6bb4e458d8e

**Comment by UcDust** [comment]
@wrenaria I think this should be deployed on dev now.

**Comment by wrenaria** [comment]
@UcDust The mystery URL is gone from filters, but I am still experiencing random reordering after hitting the "back" button.

**Comment by UcDust** [comment]
@wrenaria this should be deployed now on dev.

**Comment by wrenaria** [comment]
Looks good, result order seems to be consistent!

Unrelated maybe(?), but this item seems to be nonexistent:
https://dev.dams.library.ucdavis.edu/item/ark:/87293/d32j6886n

If I've clicked on any other items before viewing this one, then that is what shows as the item/page count. If I refresh, it shows blank with "1 of 0" for page count. 

![Screenshot 2024-11-13 at 2 33 49 PM](https://github.com/user-attachments/assets/2247fa6b-bb6c-463f-89c1-e5f55503725b)

I originally navigated to this item via this search result page https://dev.dams.library.ucdavis.edu/search//%5B%5B%22%40graph.isPartOf.%40id%22%2C%22or%22%2C%22%2Fcollection%2Fark%3A%2F87293%2Fd36q1sq2t%22%5D%5D/%5B%7B%22%40graph.name.raw%22%3A%7B%22order%22%3A%22asc%22%7D%7D%2C%7B%22%40graph.%40id%22%3A%7B%22order%22%3A%22asc%22%7D%7D%5D/20/

**Comment by UcDust** [comment]
This item page issue should be fixed with the change [here](https://github.com/ucd-library/dams/pull/212).

**Comment by wrenaria** [comment]
Looks like this fix isn't merged yet? Removing QA tag until it is.

**Comment by UcDust** [comment]
@wrenaria this should be deployed to dev now.
