### ISSUE TITLE
[UX/UI] Paging through items in search results should return user to top of list

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#226]
**Describe the bug**
Navigating to the next page of item results should return you to the top of the item list. Currently, you remain at the bottom by the pager. 

**Example screenshots/recording**

https://github.com/user-attachments/assets/e302dfd1-515d-4533-85fc-ab02f3013dc8

**Comment by UcDust** [comment]
@wrenaria I think this should be deployed on dev now.

**Comment by wrenaria** [comment]
@UcDust Looks good on Search/Items. This behavior also needs to be applied to all other pages that have pagers on them:

- [Collections](https://dev.dams.library.ucdavis.edu/browse/collections/)
- [Creators](https://dev.dams.library.ucdavis.edu/browse/creator/)
- [Subjects](https://dev.dams.library.ucdavis.edu/browse/subject)

**Comment by UcDust** [comment]
@wrenaria this should be deployed now on dev.
