### ISSUE TITLE
[UX/UI] Collection Page Admin: 0 highlights doesn't work

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#231]
**Describe the bug**
If I select `Highlight Display: 0` from any collections page admin UI, it does not work. It seems to revert to the 6 default photos on save.

**Example screenshots/recording**
This is a randomly selected collection to show the bug:

https://github.com/user-attachments/assets/87a4b145-f006-467c-8a41-35ac024bbf16

**Comment by UcDust** [comment]
@wrenaria this should be deployed now on dev.

**Comment by wrenaria** [comment]
The gold dots are part of the header and should not persist when there is no header/highlights.

---

![Screenshot 2024-11-13 at 2 07 52 PM](https://github.com/user-attachments/assets/7ebd17eb-1418-4a8c-a3a4-48ea64b76529)

**Comment by UcDust** [comment]
@wrenaria this should be patched now on dev.
