### ISSUE TITLE
[UX/UI] Video displaying as IA Reader

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#232]
**Describe the bug**
I noticed that one of highlighted items for the Greene, Henry Dart Papers collection is showing as a standard item card with IA Reader on the item page, but the item is actually a video. This issue appears to be affecting all videos in this collection.

**Collection page** with video highlight: https://dev.dams.library.ucdavis.edu/collection/ark:/87287/d7r94j/D-192 
- The video marker is missing on the cards titled "Packing fruit in California..." and "Sacramento River Association"

**Item page example:** https://dev.dams.library.ucdavis.edu/item/ark:/87293/d38z0k
- Item should be a video but is showing IA Reader

**All videos in Greene collection:** https://dev.dams.library.ucdavis.edu/search//%5B%5B%22%40graph.isPartOf.%40id%22%2C%22or%22%2C%22%2Fcollection%2Fark%3A%2F87287%2Fd7r94j%2FD-192%22%5D%2C%5B%22%40graph.fileFormatSimple%22%2C%22or%22%2C%22video%22%5D%5D/%5B%7B%22%40graph.name.raw%22%3A%7B%22order%22%3A%22asc%22%7D%7D%5D/20/
- The video marker displays on search result cards as expected
- All item pages are showing IA Reader instead of video

**Comment by UcDust** [comment]
@wrenaria this should be deployed now on dev.

**Comment by wrenaria** [comment]
Yay for videos being videos!

One piece mentioned in the issue got missed -- the cards on Collection pages should look just like the cards in search -- the type indicator is important for people to have a visual cue of what kind of content they are clicking into. 

This extends to all collections, not just Greene. For another example, [Amerine menus](https://dev.dams.library.ucdavis.edu/collection/ark:/87287/d79c7b) are multi-page items. The multi-page indicator should be there just like in search results.


Collection page item card should match --> | Search result item card
--- | ---
![Screenshot 2024-11-13 at 2 23 37 PM](https://github.com/user-attachments/assets/56a80d64-4477-459b-802c-e1aa68db5cd5) | ![Screenshot 2024-11-13 at 2 23 52 PM](https://github.com/user-attachments/assets/755b02ae-40a9-46a7-9c0f-f760be033d3d)
![Screenshot 2024-11-13 at 2 21 23 PM](https://github.com/user-attachments/assets/ca918784-96f9-445f-b4ad-eb238d68ff9e) | ![Screenshot 2024-11-13 at 2 21 48 PM](https://github.com/user-attachments/assets/06e99f47-5c6e-4156-955a-9d80e2feff78)
