### ISSUE TITLE
[UX/UI] Mobile: Margin size appears to be desktop size on "Cite this..." block

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#235]
**Describe the issue**
Minor UX/design issue but might affect readability -- The margin in the "Cite this"  blocks appears to be using desktop sizes but should be using mobile size margins. 

Examples of correct margins are [available on Figma](https://www.figma.com/design/0HdrTzkUb4E9L0DROYdmIw/DAMS?node-id=5-4), if helpful. 

Browser: iOS, Chrome

**Example screenshots/recording**
Current | With mobile margins (Figma screenshot) 
--- | ---
<img src="https://github.com/user-attachments/assets/574d4294-deaa-4846-85c2-edc01f81113b" width="320"> | ![Screenshot 2024-11-07 at 4 01 49 PM](https://github.com/user-attachments/assets/27f4cb83-7e71-4bf2-8a1d-f8af939b3a9e)

**Comment by wrenaria** [comment]
I think this might also be happening within the blue "part of collection" cards as well.

**Comment by UcDust** [comment]
@wrenaria this should be deployed now on dev.
