### ISSUE TITLE
[UX/UI] Footer clipping issue on mobile

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#243]
**Describe the bug**
Probably from the updates recently to give the main content a height of 100vh so things don't jump around on load (ie the footer showing up at the top of the page for a split second), it appears the main content is overlapping the footer on some devices/orientations. Like Android phones/tablets.

Also need to remove extra space if content isn't 100vh.

**Comment by wrenaria** [comment]
Video to demonstrate issue:

https://github.com/user-attachments/assets/fa17e7a0-8dcf-44ed-b1ce-bfbd28376410

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.

**Comment by wrenaria** [comment]
The footer is no longer clipped, but still getting some weird behavior. When I refresh a ton of extra space appears on the Browse Formats page, and at some scales, there is a lot of unnecessary white space under the Browse buttons that pushes the footer down out of sight.

Video:

https://github.com/user-attachments/assets/07b1e856-9cc6-4de1-94c5-c19a58867830

**Comment by UcDust** [comment]
@wrenaria this should be deployed to dev now.
