### ISSUE TITLE
[UX/UI] Download components file format label misaligns with download button 

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#246]
**Describe the bug**
When the label is longer (or mobile space is smaller) and text wraps to 2 lines, the download button looks bad next to the label.

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.

**Comment by wrenaria** [comment]
I don't see issues with button size, but I also didn't not see the original wrapping problem and there is no screenshot, so I don't have any way to compare my view to the original problem. 

I do see that when you choose "all files" it just shows a download button and no file info (type or size), which is not ideal. Shouldn't it say something like  `zip (Xmb)` at least? Mystery sized downloads are not ideal. 

![Screenshot 2024-12-09 at 3 46 29 PM](https://github.com/user-attachments/assets/acd9d423-ab91-44b6-98e1-a6de109d3721)

**Comment by UcDust** [comment]
@wrenaria this should be deployed to dev now.
