### ISSUE TITLE
[UX/UI] Browse header link render ordering issue in Firefox

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#249]
**Describe the bug**
It looks like the search header is rendering on top of the browse links in the header navigation in Firefox.

![image](https://github.com/user-attachments/assets/365fc44b-dc88-45e7-906d-9c40ce654d17)

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.

**Comment by wrenaria** [comment]
Look okay to me, but can you take a look @rakunkel-ucd since you identified this issue originally? Feel free to close the issue if it looks resolved.

**Comment by rakunkel-ucd** [comment]
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rakunkel-ucd** [comment]
Looks good - FF OS X
