### ISSUE TITLE
[UX/UI] Bookreader not rendering an item

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#256]
It looks like [this item](https://dev.dams.library.ucdavis.edu/item/ark:/87293/d3xk84v4h) isn't rendering correctly. Could this be related to the uncommitted change at https://github.com/ucd-library/dams/pull/212/commits/da4ced214cee4cc66003058d547a1b7cdeaf81bd#diff-580c1d580f17efad52df5a0578e655339dc316ad076a4b53053ff7a3aace6caa?

Also [this item](https://dev.dams.library.ucdavis.edu/item/ark:/87293/d3xk84v4h) might have the same issue, but test it.

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.

**Comment by wrenaria** [comment]
@UcDust It looks like there is supposed to be two different items linked in your original comment? Both links go to the same item.

**Comment by UcDust** [comment]
@wrenaria sorry actually it's just the one item for this issue, so I think we're good.
