### ISSUE TITLE
[UX/UI] Update about page links

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#260]
During testing, this was noted:
_Is there a reason Eric's contact link opens as an mailto instead of going to his directory entry? It was very jarring experience when the rest of the names are directory links. Either it should to be explicitly labeled/listed as an email or go to his profile instead (which has his email in it)._

**Comment by wrenaria** [comment]
Just link to his library profile page. I am okay with the link being repeated later on as it is in a different context.

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.
