### ISSUE TITLE
[UX/UI] Homepage mobile layout changes

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#269]
During testing, it was mentioned: 

Content at mobile size should all fill available width, otherwise, it is harder to read things on smaller devices and looks wonky when there is no whitespace to balance out the width changes.

The content that uses less than full width on desktop should work like shrink on PatternLab: [https://library.ucdavis.edu/collections/](https://www.google.com/url?q=https://library.ucdavis.edu/collections/&sa=D&source=editors&ust=1732119183811839&usg=AOvVaw1IOsKTGkvPpNfEfG4dSIXx)
Example of this implemented on the library website: [https://library.ucdavis.edu/collections/](https://www.google.com/url?q=https://library.ucdavis.edu/collections/&sa=D&source=editors&ust=1732119183811953&usg=AOvVaw2RyKgJ0Q7ggQgggJP4nAyJ)

If possible, the centered text converting to left-aligned at the mobile range would be best for readability, but definitely not a dealbreaker if its a pain to implement.

Screenshot from DAMS:
[https://drive.google.com/file/d/140dGrYTsGfupQKJOrMoKdbK4yoAtpVEz/view?usp=drive_link](https://www.google.com/url?q=https://drive.google.com/file/d/140dGrYTsGfupQKJOrMoKdbK4yoAtpVEz/view?usp%3Ddrive_link&sa=D&source=editors&ust=1732119183812024&usg=AOvVaw0hULY3GI8RW8P7CuukV4S0)

Screenshot from Figma:
[https://drive.google.com/file/d/141ORDzKG19-MVPMtbCqP_CN6S_CZEOsV/view?usp=drive_link](https://www.google.com/url?q=https://drive.google.com/file/d/141ORDzKG19-MVPMtbCqP_CN6S_CZEOsV/view?usp%3Ddrive_link&sa=D&source=editors&ust=1732119183812076&usg=AOvVaw3JSoOwF_LLii1xlyd1a0-a)

Figma File:
[https://www.figma.com/design/0HdrTzkUb4E9L0DROYdmIw/DAMS?node-id=324-1789&t=YnU3ebpiGJzCW5M5-1](https://www.google.com/url?q=https://www.figma.com/design/0HdrTzkUb4E9L0DROYdmIw/DAMS?node-id%3D324-1789%26t%3DYnU3ebpiGJzCW5M5-1&sa=D&source=editors&ust=1732119183812123&usg=AOvVaw28C34dqjtwr9bWzWHyg6ls)

**Comment by UcDust** [comment]
@wrenaria this should be ready to test on dev.

**Comment by wrenaria** [comment]
Looks good! Thanks!
