### ISSUE TITLE
[UX/UI] Single page view issue in bookreader

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#271]
[This item](https://dev.dams.library.ucdavis.edu/item/ark:/87293/d3k649x7h), at least for Android phones in Chrome, doesn't display when single page mode. Only shows images in 2 page mode.

**Comment by wrenaria** [comment]
I am seeing this issue on desktop for all browsers with the item mentioned above and others.

More examples:
- https://dev.dams.library.ucdavis.edu/item/ark:/87293/d36m3378w
- https://dev.dams.library.ucdavis.edu/item/ark:/87293/d3000047m
- https://dev.dams.library.ucdavis.edu/item/ark:/87293/d3mw28k0p

**Comment by UcDust** [comment]
This is fixed with the change in https://github.com/ucd-library/dams/commit/187908d066cdab531dc66b109ec0d80843b8b6fa.
