### ISSUE TITLE
[UX/UI] Can't access nav buttons in bookreader fullscreen on iPhone

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#272]
Cannot access the controls in full screen mode after performing an in-item text search, they are hidden behind the address bar. 

[https://drive.google.com/file/d/14VNOsMlIMGJa2DcbTpubeY3DaRw3jA2y/view?usp=drive_link](https://www.google.com/url?q=https://drive.google.com/file/d/14VNOsMlIMGJa2DcbTpubeY3DaRw3jA2y/view?usp%3Ddrive_link&sa=D&source=editors&ust=1732119183802870&usg=AOvVaw293vkPG7HlVBJvJQQ8GrjW)

Also same problem as desktop where cannot actually view the full item in full screen since the controls block the lower portion of the item and it won't let you zoom our further.

**Comment by UcDust** [comment]
@wrenaria I can't seem to replicate this now, I tested with safari and chrome. Can you see if it's still a problem for you? 

We did make some changes to the view height of the main content of the app in another issue, so it's possible it was fixed from those changes. However if you can reproduce still, I could track it down further.

**Comment by wrenaria** [comment]
Seems to be resolved!
