### ISSUE TITLE
[UX/UI] ASC change - collection metadata disclaimer updates

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#276]
- [x] The disclaimer should be toggle-able with admin preferences, and default to not show.
- [x] The disclaimer should be moved lower on the page (tbd).

**Comment by UcDust** [comment]
@EricNebeker 

In case it's useful, here's a screenshot with a potential change from Kimmy. I'll work on the other aspects of this issue, and circle back next week to repositioning the disclaimer as needed.

<img width="1136" alt="Screenshot 2024-12-03 at 15 44 02" src="https://github.com/user-attachments/assets/9a8c3edc-3def-4e11-b3c7-0cc8612371e5">

**Comment by UcDust** [comment]
For toggling the disclaimer, the admin ui will look like this-

![Screenshot 2024-12-04 at 08 22 04](https://github.com/user-attachments/assets/21f7f4d5-1e4b-4a3a-8952-c2c1cb67853c)

**Comment by UcDust** [comment]
Waiting for confirmation from ASC that this is approved, and to confirm if we should move the disclaimer as shown above.

**Comment by UcDust** [comment]
@wrenaria this should be deployed to dev now.

**Comment by wrenaria** [comment]
Looks good to me. 

@EricNebeker Please close the issue after you review and approve. Also, unrelated, but I happened to use [Department of Irrigation Photographs](https://dev.dams.library.ucdavis.edu/collection/ark:/87293/d3bg2hh7f) to test this, and noticed the OAC link needs its formatting fixed. Can you please fix it?

**Comment by EricNebeker** [comment]
@wrenaria The OAC link is fixed, and several others are in the process of being fixed.

**Comment by EricNebeker** [comment]
Approve
