### ISSUE TITLE
Need a new browse-by endpoint to return specific / filtered data for Collections

### ISSUE THREAD

**Issue by UcDust** [ucd-library/dams#29]
For reference, @wrenaria's [designs](https://xd.adobe.com/view/a318aa5b-3f31-4bd5-b7e8-b67219260304-f64b/).

We need to display Collection cards with the following info:

1. Collection title/name
2. Collection ID (for url links)
3. Collection thumbnail image link
4. Total number of items in the collection
5. Timestamp of when it was added

We need a new endpoint that allows some limit / filtering / sorting params to filter for a few situations:

1. Filtered to return a set number of collections
2. Filtered by timestamp so we can get the most recently added
3. Filtered by collection title/name A-Z, like [shown here](https://xd.adobe.com/view/a318aa5b-3f31-4bd5-b7e8-b67219260304-f64b/screen/849ab49f-4834-449b-9ae3-f69663a487d2)
4. Filtered by how many items the collection contains, returning the most to least

**Comment by UcDust** [comment]
@jrmerz if it's not too much trouble, it would also be nice to have a related endpoint that we could pass a collection id into, which would return the number of items that collection has. 

This is mainly for the item page, there is a card with a reference to the collection and how many [items it contains](https://xd.adobe.com/view/a318aa5b-3f31-4bd5-b7e8-b67219260304-f64b/screen/ebc5a386-1880-4c9b-8f87-68a0c7b079cc).

**Comment by UcDust** [comment]
@jrmerz ok! I've made https://github.com/ucd-library/dams/issues/30

**Comment by jrmerz** [comment]
@UcDust itemCount has been added to the rootNode of a collection in the api. 

FYI. the digitized date will be something we need to add to the data.  I it will node be a fcrepo or elasticsearch timestamp thing.

**Comment by jrmerz** [comment]
The item model needs to send a reindex event for any isPartOf fin id, so the collection is reindexed
