### ISSUE TITLE
Sitewide text style issues

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#64]
There are a number of text style issues where styles are incorrect sizes or missing styles. 

**Global:** Headers with gold dots are missing their dots. 

Some H sizes appear to have unnecessary overrides. For example, Collection page headings should display the standard H1 size for the page title.

Collection Title with Current Override | Desired Title with Default h1 Style
--- | ---
![Screen Shot 2023-07-06 at 10 53 32 AM](https://github.com/ucd-library/dams/assets/17831969/6b4ac740-fe09-43a9-9b76-961a40918296) | ![Screen Shot 2023-07-06 at 10 53 44 AM](https://github.com/ucd-library/dams/assets/17831969/f3c45c3e-9efc-4d60-9fc1-cfa932f56fc3)

There is a breakdown of expected DAMS text styles listed out on Library Stage: https://stage.library.ucdavis.edu/dams-text-styles/ 

I can go into more in-depth review and breakdown page by page if need be.

**Comment by UcDust** [comment]
@wrenaria This description should be enough depth for the heading styles. But could you also point out other text size issues you've noticed other than headings?

**Comment by wrenaria** [comment]
I'm still seeing a few text issues.

The main "Digital Collections" title (and everything else at this font size) is heavier weight than it should be and the text sentence that appears below it is supposed to be larger (same size as h4 styles I think? Is that 1.42rem-ish?) 

![Screen Shot 2023-08-04 at 4 10 03 PM](https://github.com/ucd-library/dams/assets/17831969/63995515-3977-4ab6-af42-efcafee7f0ed)

In addition to being too heavy, they (and any other headers that are supposed to have them) are missing their gold dots.

![Screen Shot 2023-08-04 at 4 15 45 PM](https://github.com/ucd-library/dams/assets/17831969/a097cbe0-3eb4-4d0f-95a3-56cf438ea46d)

The dot between these items is pulsing for some reason?

https://github.com/ucd-library/dams/assets/17831969/a0844046-b810-465f-bba2-df32c5808f0f

h3 styled headers on Item pages (where the item title is) are too light weight. They should be set 800, they are currently set to 700, and when I change them via Inspector, they look too fat, so I'd maybe check that you have the right font file loaded. Wrong font file might explain the other fat headers too, since looking in Inspector the style settings look like they are the right number value. Or maybe something else is going on, IDK.
