### ISSUE TITLE
Collection Page: Collection numbers missing on some collections

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#66]
Collection numbers have disappeared from some collections.

For example, Amerine Menu Collection used to display "Collection #D-060" under the title, but it is gone now.

## Screenshot from 6/15:

![Screen Shot 2023-06-15 at 10 37 33 AM](https://github.com/ucd-library/dams/assets/17831969/7809e2cb-202e-44a9-85ec-a8eb869cf845)

## Screenshot from today:

![Screen Shot 2023-07-06 at 4 36 36 PM](https://github.com/ucd-library/dams/assets/17831969/91a71863-e9fb-4a5f-9814-b3074e3f3c61)

**Comment by UcDust** [comment]
@wrenaria I think this will be a data issue that needs to be fixed. The call numbers should come from the `Identifier` in fcrepo, for instance https://sandbox.dams.library.ucdavis.edu/fcrepo/rest/collection/ark:/87287/d79c7b. The sandbox collections are being taken directly from the production environment, and many of those collections are missing the call number. 

Eric (or someone on the team) will need to update the collection data in fcrepo in order for those numbers to show up in the ui.

**Comment by wrenaria** [comment]
@UcDust My confusion comes from it having been there previously. Was the data removed? Because the 6/15 screenshot above is from Sandbox itself, not my mockups, so if the collection number data didn't exist before, where was that  collection number D-060 coming from???

**Comment by UcDust** [comment]
@wrenaria We had constructed some sample data to test with, so previously in sandbox, we had a small subset of the collection and some data was created that isn't actually in production. 

The current data exports/imports are being created directly from the live digital site though, so since it's missing in production it also will on sandbox.

**Comment by wrenaria** [comment]
@UcDust Got it! That clears things up for me. Thanks for the explanation.
