### ISSUE TITLE
Mobile: Item Page - Hard to scroll past Bookreader UI

### ISSUE THREAD

**Issue by wrenaria** [ucd-library/dams#76]
The PDF viewer takes up too much real estate on mobile screens. I have to scroll through the whole PDF doc before I can get to and see the item data. Even after scrolling down, it can be a challenge to get past the image data. At first, I though it was just not loading the page text content at all and only showing me images, but that is not the case. 

Not sure the best approach for this. Take up a certain percentage of screen at mobile sizes on load? We need somewhere at the bottom of the screen for people to be able to flick their thumbs and scroll past the image content without having to view every page.

## Video of Issue
- See how the scroll bounces to a stop at the bottom of the PDF, so this is why I thought the rest of the item page was missing at first.
- Also note that the pager shows that I am on page 3 of 5, even though I am on the last page. 

https://github.com/ucd-library/dams/assets/17831969/09f31753-7c96-4b7a-996e-9e84bb134cd8

## Screenshots of Issue

Example 1 | Example 2 | Example 3
--- | --- | ---
![IMG_5779](https://github.com/ucd-library/dams/assets/17831969/fb1245b3-1ad7-4eb4-b853-c8050fce5daa) | ![IMG_5780](https://github.com/ucd-library/dams/assets/17831969/947bb15a-4ce6-4f69-a4ab-acea524accea) | ![IMG_5778](https://github.com/ucd-library/dams/assets/17831969/a540dac0-21eb-4434-b382-dfa6266dcbbd)

**Comment by UcDust** [comment]
@wrenaria I've experimented in the browser simulating mobile but it's a little hard to tell which experience is better. We could potentially have the bookreader take up around 60-70% view height to allow some of the page to be draggable below the bookreader. Alternatively we could make the bookreader take up around 75% view width and allow the page to be draggable from the left/right sides. 

If we could collapse the search header somewhat, that may also help. 

If you'd like to chat and screenshare I could show you how the layouts could look. If none of this sounds good though, perhaps we could bring it up in the OS dev slack/meeting to see if others have ideas.

**Comment by UcDust** [comment]
@wrenaria this is at 60% viewport height, seems to function pretty well. 

![Image](https://github.com/ucd-library/dams/assets/103536473/1503cace-49fe-41dd-a07e-98c1db9a0669)

**Comment by wrenaria** [comment]
Sorry, I super missed this request. Can we look at this together on Zoom next week? Just ping me on Slack, or feel free to schedule a time that works for you that doesn't collide with my other meetings.

**Comment by UcDust** [comment]
@wrenaria no worries at all. I think potentially this task could be closed once we finish the other mobile ui task, since we're now disabling the ability to scroll inside the bookreader, and instead just leveraging the slider and previous/next buttons to navigate.
